name: "test-greeting"

on:
  workflow_dispatch:
    inputs:
      greet:
        description: "What should we say?"
        default: "Hello World!"

jobs:
  test1:
    runs-on: automati
    steps:
    - run: echo ${{ github.event.inputs.greet }}

  test2:
    runs-on: automati
    needs: test1
    steps:
    - run: echo ${{ github.event.inputs.greet }}

  test3:
    runs-on: automati
    needs: test1
    steps:
      - run: echo ${{ github.event.inputs.greet }}

  test4:
    runs-on: automati
    needs: test2
    strategy:
      fail-fast: false
      matrix:
        greet: [one, two, three]
    steps:
      - run: echo "${{ matrix.greet }} - ${{ github.event.inputs.greet }}"

  test5:
    runs-on: automati
    needs: [test4, test3]
    steps:
      - run: echo ${{ github.event.inputs.greet }}
