name: Update Nuclei Templates
on:
  workflow_dispatch:
  schedule: [{"cron": "0 0 * * *"}]

jobs:
  update-nuclei-templates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      - name: Add Git config
        run: |
          git config --global user.email "${{ secrets.GLOBAL_GITHUB_EMAIL }}"
          git config --global user.name "${{ secrets.GLOBAL_GITHUB_USER }}"
          cd config/nuclei/nuclei-templates/
          git reset --hard HEAD
          cd ../../../

      - name: Update templates
        run: git submodule foreach git pull origin main

      - run: |
          git add config/nuclei/nuclei-templates/
          git diff-index --quiet HEAD || git commit -m "${{ github.workflow }} - Run ${{ github.run_id }}" --allow-empty
          git push -f
